pub mod ai;
pub mod animation;
pub mod app;
pub mod app_modular;
pub mod calendar;
pub mod cli;
pub mod clipboard;
pub mod config;
pub mod contacts;
pub mod email;
pub mod encryption;
pub mod events;
pub mod html;
pub mod images;
pub mod imap;
pub mod keyboard;
pub mod maildir;
pub mod mime;
pub mod mobile;
pub mod notifications;
pub mod oauth2;
pub mod offline_storage;
pub mod performance;
pub mod rfc_standards;
pub mod plugins;
pub mod services;
pub mod smtp;
pub mod spell;
pub mod startup;
pub mod system;
pub mod tea;
pub mod theme;
pub mod ui;

#[cfg(test)]
pub mod integration_test;

pub use app::App;
pub use app_modular::ModularApp;
